CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL
);

INSERT INTO users (name) VALUES ('Alice') ON CONFLICT DO NOTHING;
INSERT INTO users (name) VALUES ('Bob') ON CONFLICT DO NOTHING;
